### ISSUE TITLE
Typo in Location Schema?

### ISSUE THREAD

**Issue by manleung235** [jessicawlm/Group_Proj#1]
I find a error about the type of ref 'User'  in   userComments:[{body: String, username: ObjectId, ref:'User', date: Date}]

 throw new TypeError(`Invalid schema configuration: \`${name}\` is not ` +
    ^
TypeError: Invalid schema configuration: `User` is not a valid type at path `ref`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.

do you mean  userComments:[{body: String, type: ObjectId, ref:'User', date: Date}]????

**Comment by mcchow8** [comment]
At the beginning, I want to save the username into the userComments, so I choose the ObjectId of username.
But I think userComments:[{body: String, username: String , date: Date}] is also OK.
Sorry about that.

**Comment by manleung235** [comment]
nvm :)
